-- Dunning reminders sent per (account, milestone, expiry-cycle). The unique
-- key makes the daily scheduler idempotent: a milestone fires once per
-- account per expiry date, and renewing (new expiry_date) re-arms the cycle.
CREATE TABLE IF NOT EXISTS dunning_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    milestone VARCHAR(16) NOT NULL,
    expiry_date DATE NOT NULL,
    sms_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dunning_account FOREIGN KEY (account_id)
        REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT uq_dunning UNIQUE (account_id, milestone, expiry_date)
);

CREATE INDEX IF NOT EXISTS idx_dunning_account ON dunning_log(account_id);
